## Challenges

In [ ]:
import pandas as pd
data1 = {
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco', 'London', 'Paris', 'Berlin', 'Rome', 'Tokyo'],
    'Country': ['USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'France', 'Germany', 'Italy', 'Japan'],
    'Population (Millions)': [8.4, 3.9, 2.7, 2.3, 0.9, 8.9, 2.1, 3.7, 2.8, 13.9],
    'Area (km2)': [468.9, 502.8, 227.6, 1, 121.4, 1572, 105.4, 891.8, 1285, 2187],
    'Language': ['English', 'English', 'English', 'English', 'English', 'English', 'French', 'German', 'Italian', 'Japanese'],
    'Currency': ['USD', 'USD', 'USD', 'USD', 'USD', 'GBP', 'EUR', 'EUR', 'EUR', 'JPY'],
    'Continent': ['North America', 'North America', 'North America', 'North America', 'North America', 'Europe', 'Europe', 'Europe', 'Europe', 'Asia'],
    'Is_Capital': [False, False, False, False, False, True, True, True, True, True]
}

cities_info = pd.DataFrame(data1)
cities_info

,City,Country,Population (Millions),Area (km2),Language,Currency,Continent,Is_Capital
0,New York,USA,8.4,468.9,English,USD,North America,False
1,Los Angeles,USA,3.9,502.8,English,USD,North America,False
2,Chicago,USA,2.7,227.6,English,USD,North America,False
3,Houston,USA,2.3,1.0,English,USD,North America,False
4,San Francisco,USA,0.9,121.4,English,USD,North America,False
5,London,UK,8.9,1572.0,English,GBP,Europe,True
6,Paris,France,2.1,105.4,French,EUR,Europe,True
7,Berlin,Germany,3.7,891.8,German,EUR,Europe,True
8,Rome,Italy,2.8,1285.0,Italian,EUR,Europe,True
9,Tokyo,Japan,13.9,2187.0,Japanese,JPY,Asia,True

In [ ]:
data2 = {
    'City': ['New York', 'Chicago', 'Houston', 'London', 'Paris', 'Berlin', 'Rome', 'Tokyo', 'Lagos'],
    'Temperature (Celsius)': [18, 21, 30, 15, 19, 20, 24, 29, 34],
    'Humidity (%)': [65, 70, 75, 75, 80, 68, 72, 74, 83],
    'Rainfall (mm)': [50, 75, 20, 60, 40, 45, 35, 10, 122],
}

cities_weather = pd.DataFrame(data2)
cities_weather

       City  Temperature (Celsius)  Humidity (%)  Rainfall (mm)
0  New York                     18            65             50
1   Chicago                     21            70             75
2   Houston                     30            75             20
3    London                     15            75             60
4     Paris                     19            80             40
5    Berlin                     20            68             45
6      Rome                     24            72             35
7     Tokyo                     29            74             10
8     Lagos                     34            83            122

### Challenge 1
Calculate the average population of cities in each continent using the groupby method

In [ ]:
avg_population_by_continent = (
    cities_info
    .groupby('Continent')['Population (Millions)']
    .mean()
)

avg_population_by_continent

Continent
Asia             13.900
Europe            4.375
North America     3.640
Name: Population (Millions), dtype: float64

### Challenge 2
Find the city with the highest population in each country using the groupby method and agg function

In [ ]:
Find the city with the highest population in each country using the groupby method and agg function

SyntaxError: invalid syntax (ipython-input-3532782039.py, line 1)

In [ ]:
max_pop = cities_info.groupby("Country").agg({"Population (Millions)":"max"})
largest_cities = pd.merge(cities_info, max_pop,
on=["Country", "Population (Millions)"],
how="inner")[["City", "Country", "Population (Millions)"]]
largest_cities

       City  Country  Population (Millions)
0  New York      USA                    8.4
1    London       UK                    8.9
2     Paris   France                    2.1
3    Berlin  Germany                    3.7
4      Rome    Italy                    2.8
5     Tokyo    Japan                   13.9

### Challenge 3
Merge the cities_info and cities_weather DataFrames using a right join to keep only the cities for which weather data is available.

In [ ]:
merged_df = pd.merge(
    cities_info,
    cities_weather,
    on='City',
    how='right'
)

merged_df

,City,Country,Population (Millions),Area (km2),Language,Currency,Continent,Is_Capital,Temperature (Celsius),Humidity (%),Rainfall (mm)
0,New York,USA,8.4,468.9,English,USD,North America,False,18,65,50
1,Chicago,USA,2.7,227.6,English,USD,North America,False,21,70,75
2,Houston,USA,2.3,1.0,English,USD,North America,False,30,75,20
3,London,UK,8.9,1572.0,English,GBP,Europe,True,15,75,60
4,Paris,France,2.1,105.4,French,EUR,Europe,True,19,80,40
5,Berlin,Germany,3.7,891.8,German,EUR,Europe,True,20,68,45
6,Rome,Italy,2.8,1285.0,Italian,EUR,Europe,True,24,72,35
7,Tokyo,Japan,13.9,2187.0,Japanese,JPY,Asia,True,29,74,10
8,Lagos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34,83,122

### Challenge 4
Group the cities by their 'Language' and find the total area and total rainfall for each language group

In [ ]:
merged_df = cities_info.merge(cities_weather, on='City')
language_group = merged_df.groupby('Language')[['Area (km2)', 'Rainfall (mm)']].sum()
language_group

          Area (km2)  Rainfall (mm)
Language
English       2269.5            205
French         105.4             40
German         891.8             45
Italian       1285.0             35
Japanese      2187.0             10

### Challenge 5
Calculate the sum of rainfall in each country using the groupby method.

In [ ]:
merged_df = pd.merge(
    cities_info,
    cities_weather,
    on='City',
    how='inner'
)

rainfall_by_country = (
    merged_df
    .groupby('Country')['Rainfall (mm)']
    .sum()
)

rainfall_by_country

### Challenge 6
Group the cities by their 'Continent' and find the average temperature and humidity for each continent

In [ ]:
merged_df.groupby('Continent')[['Temperature (Celsius)', 'Humidity (%)']].mean()

               Temperature (Celsius)  Humidity (%)
Continent
Asia                            29.0         74.00
Europe                          19.5         73.75
North America                   23.0         70.00

### Challenge 7
Group the cities by their 'Is_Capital' and 'Language' columns and find the maximum population and minimum area for each combination.

In [ ]:
cities_info.groupby(['Is_Capital','Language']).agg({'Population (Millions)':'max', 'Area (km2)':'min'}).reset_index()